//! Repo package scaffolding for the Crystal target.
//!
//! Crystal binds over the shared C FFI crate (like Go and Zig), so there is no
//! dedicated Rust binding crate (`scaffold_crystal_cargo`) — the `-ffi` crate is
//! scaffolded by [`super::ffi::scaffold_ffi`]. This emits the Crystal *package*
//! files: the `shard.yml` manifest plus the conventional project furniture
//! (`.gitignore`, `.editorconfig`, README, an example, and a smoke spec so
//! `crystal spec` passes out of the box), mirroring `scaffold_zig` /
//! `scaffold_gleam`.

use crate::core::backend::GeneratedFile;
use crate::core::config::{Language, ResolvedCrateConfig};
use crate::core::ir::ApiSurface;
use crate::scaffold::scaffold_meta;
use std::path::PathBuf;

pub(crate) fn scaffold_crystal(api: &ApiSurface, config: &ResolvedCrateConfig) -> anyhow::Result<Vec<GeneratedFile>> {
    let meta = scaffold_meta(config);
    let version = &api.version;
    let shard_name = config.name.replace('-', "_");
    let description = meta.description.clone();
    let license = meta.license.as_deref().unwrap_or("MIT");
    let dir = config.package_dir(Language::Crystal);

    let shard_yml = format!(
        r#"name: {shard_name}
version: {version}

description: |
  {description}

crystal: ">= 1.0.0"

license: {license}
"#
    );

    // shards installs into `lib/`, `shards build` into `bin/`; `.shards/` is the
    // resolver cache. `*.dwarf` is emitted alongside debug builds on macOS.
    let gitignore = "/lib/\n/bin/\n/.shards/\n*.dwarf\n";

    let editorconfig = "[*]\ncharset = utf-8\nend_of_line = lf\ninsert_final_newline = true\ntrim_trailing_whitespace = true\n\n[*.cr]\nindent_style = space\nindent_size = 2\n";

    let readme = format!(
        r#"# {crate_name}

{description}

Crystal bindings generated by [alef](https://github.com/kreuzberg-dev/alef).

## Installation

Add to your `shard.yml`:

```yaml
dependencies:
  {shard_name}:
    {dependency_ref}
```

Then:

```sh
shards install
```

## Usage

```crystal
require "{shard_name}"
```

## Development

```sh
shards install
crystal spec
crystal tool format
```

## License

{license}
"#,
        crate_name = config.name,
        shard_name = shard_name,
        description = description,
        dependency_ref = crystal_dependency_ref(&meta),
        license = license,
    );

    let example = format!(
        r#"require "../src/{shard_name}"

# Example: call into the generated {module_name} bindings.
# Replace with your actual API calls after code generation.
puts {module_name}::VERSION
"#,
        shard_name = shard_name,
        module_name = crate::backends::crystal::type_map::crystal_type_name(&config.name),
    );

    let spec_helper = format!("require \"spec\"\nrequire \"../src/{shard_name}\"\n");

    // Smoke spec so a freshly scaffolded package passes `crystal spec` before the
    // consumer adds real assertions. Mirrors the Gleam `gleeunit` smoke test.
    let smoke_spec = format!(
        r#"require "./spec_helper"

describe {module_name} do
  it "exposes a version" do
    {module_name}::VERSION.should_not be_empty
  end
end
"#,
        module_name = crate::backends::crystal::type_map::crystal_type_name(&config.name),
    );

    Ok(vec![
        GeneratedFile {
            path: PathBuf::from(format!("{dir}/shard.yml")),
            content: shard_yml,
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from(format!("{dir}/.gitignore")),
            content: gitignore.to_string(),
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from(format!("{dir}/.editorconfig")),
            content: editorconfig.to_string(),
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from(format!("{dir}/README.md")),
            content: readme,
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from(format!("{dir}/examples/example.cr")),
            content: example,
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from(format!("{dir}/spec/spec_helper.cr")),
            content: spec_helper,
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from(format!("{dir}/spec/{shard_name}_spec.cr")),
            content: smoke_spec,
            generated_header: false,
        },
    ])
}

/// Resolve the `shard.yml` dependency reference for the README, preferring a
/// configured GitHub repository over a local path fallback.
fn crystal_dependency_ref(meta: &crate::scaffold::ScaffoldMeta) -> String {
    let Some(repository) = meta.configured_repository.as_deref() else {
        return "path: ../packages/crystal".to_string();
    };
    let github_path = repository
        .strip_prefix("https://github.com/")
        .or_else(|| repository.strip_prefix("http://github.com/"))
        .map(|path| path.trim_end_matches('/').trim_end_matches(".git"));
    if let Some(path) = github_path
        && !path.is_empty()
    {
        return format!("github: {path}");
    }
    format!("git: {}", repository.trim_end_matches(".git"))
}
